version: "2.1"
services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    ports:
      - 6881:6881
      - 6881:6881/udp
      # - 8080:8080
    volumes:
      - config:/config
      - ${DOWNLOAD_FOLDER}:/downloads
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
# Required for Traefik
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.qbit.entrypoints=websecure"
      - "traefik.http.routers.qbit.rule=Host(${HTTP_HOST})"
      # HTTP Services
      - "traefik.http.routers.qbit.service=qbit"
      - "traefik.http.services.qbit.loadbalancer.server.port=${HTTP_PORT}"
      # Middlewares
      - "traefik.http.routers.uptime.middlewares=chain-default@file"
networks:
  proxy:
    external: true
# Required for Traefik
volumes:
  config:
