version: "3.1"
services:
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    # ports:
      # - 80:80
    volumes:
      - config:/config
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
# Required for Traefik
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.heimdall.entrypoints=websecure"
      - "traefik.http.routers.heimdall.rule=Host(${HTTP_HOST})"
      # HTTP Services
      - "traefik.http.routers.heimdall.service=heimdall"
      - "traefik.http.services.heimdall.loadbalancer.server.port=${HTTP_PORT}"
networks:
  proxy:
    external: true
# Required for Traefik
volumes:
  config:
