version: "3.1"
services:
  guacamole:
    image: flcontainers/guacamole
    container_name: guacamole
    environment:
      - EXTENSIONS=auth-totp
    volumes:
      - postgres:/config
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guacamole.entrypoints=https"
      - "traefik.http.routers.guacamole.rule=Host(${HTTP_HOST})"
      - "traefik.http.routers.guacamole.tls=true"
      - "traefik.http.routers.guacamole.service=guacamole"
      - "traefik.http.services.guacamole.loadbalancer.server.port=${HTTP_PORT}"
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true
volumes:
  postgres:
