version: "3.1"
services:
  guacamole:
    image: flcontainers/guacamole:latest
    container_name: guacamole
    # ports:
      # - 8080:8080
    volumes:
      - postgres:/config
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - EXTENSIONS=auth-totp
# Required for Traefik
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guacamole.entrypoints=https"
      - "traefik.http.routers.guacamole.rule=Host(${HTTP_HOST})"
      - "traefik.http.routers.guacamole.tls=true"
      - "traefik.http.routers.guacamole.service=guacamole"
      - "traefik.http.services.guacamole.loadbalancer.server.port=${HTTP_PORT}"
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true
# Required for Traefik
volumes:
  postgres:
