version: "2"
services:
  homer:
    image: b4bz/homer
    container_name: homer
    restart: unless-stopped
    volumes:
      - assets:/www/assets
# Required for Traefik
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homer.entrypoints=https"
      - "traefik.http.routers.homer.rule=Host(${HTTP_HOST})"
      - "traefik.http.routers.homer.tls=true"
      - "traefik.http.routers.homer.service=homer"
      - "traefik.http.services.homer.loadbalancer.server.port=${HTTP_PORT}"
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true
# Required for Traefik
volumes:
  assets:
