version: "2.1"
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    command: tunnel run
# Required for Traefik
    networks:
      proxy:
networks:
  proxy:
    external: true
# Required for Traefik