version: "2"
services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    volumes:
      - work:/opt/adguardhome/work
      - conf:/opt/adguardhome/conf
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      vlan:
        ipv4_address: 192.168.1.250
networks:
  vlan:
    external: true
volumes:
  work:
  conf: