version: '3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    # ports:
      # - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
# Required for Traefik
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=https"
      - "traefik.http.routers.portainer.rule=Host(${HTTP_HOST})"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=${HTTP_PORT}"
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true
# Required for Traefik