version: '3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    # ports:
      # - 9000:9000
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
# Required for Traefik and Socket
    networks:
      - proxy
      - socket
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.rule=Host(${HTTP_HOST})"
      # HTTP Services
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=${HTTP_PORT}"
      # Middlewares
      - "traefik.http.routers.portainer.middlewares=chain-default@file"
networks:
  proxy:
    external: true
  socket:
    external: true
# Required for Traefik and Socket