version: "3.1"
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    # ports:
      # - 3001:3001
    volumes:
      - data:/app/data
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
# Required for Traefik and Socket
    networks:
      - proxy
      - socket
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.uptime.entrypoints=websecure"
      - "traefik.http.routers.uptime.rule=Host(${HTTP_HOST})"
      # HTTP Services
      - "traefik.http.routers.uptime.service=uptime"
      - "traefik.http.services.uptime.loadbalancer.server.port=${HTTP_PORT}"
      # Middlewares
      - "traefik.http.routers.uptime.middlewares=middleware-secure-headers@file"
networks:
  proxy:
    external: true
  socket:
    external: true
# Required for Traefik and Socket
volumes:
  data: