version: "2.1"
services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    ports:
      - 51820:51820/udp
    volumes:
      - config:/config
      - modules:/lib/modules
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
      - SERVERURL=${EXTERNAL_HOST}
      - PEERS=1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1 
volumes:
  config:
  modules: