version: "2"
secrets:
  admin_pwd:
    file: /docker/secrets/admin_pwd
  access_key:
    file: /docker/secrets/access_key
services:
  semaphore:
    image: semaphoreui/semaphore:latest
    container_name: semaphore
    # ports:
      # - 3000:3000
    volumes:
      - data:/var/lib/semaphore
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    secrets:
      - admin_pwd
      - access_key
    environment:
      - SEMAPHORE_DB_DIALECT=bolt
      - SEMAPHORE_ADMIN_PASSWORD_FILE=/run/secrets/admin_pwd
      - SEMAPHORE_ADMIN_NAME=admin
      - SEMAPHORE_ADMIN_EMAIL=admin@localhost
      - SEMAPHORE_ADMIN=admin
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION_FILE=/run/secrets/access_key 
      - ANSIBLE_HOST_KEY_CHECKING=false
# Required for Traefik
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.semaphore.entrypoints=websecure"
      - "traefik.http.routers.semaphore.rule=Host(${HTTP_HOST})"
      # HTTP Services
      - "traefik.http.routers.semaphore.service=semaphore"
      - "traefik.http.services.semaphore.loadbalancer.server.port=${HTTP_PORT}"
      # Middlewares
      - "traefik.http.routers.semaphore.middlewares=chain-default@file"
networks:
  proxy:
    external: true
# Required for Traefik
volumes:
  data:
